version: "3"
services:
  nginx:
    ports:
      - "3000:80"
  node-app:
    build:
      context: .
      args: 
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=bassel
      - MONGO_PASSWORD=mypassword
      - SESSION_SECRET=secret
    command: npm start
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=bassel
      - MONGO_INITDB_ROOT_PASSWORD=mypassword 

